POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Testing Conference",
  "details": "A conference for developers",
  "maximumAttendees": 150
}

###

POST http://localhost:3333/events/8beca352-9c53-4b55-8bc4-512af96d7efc/attendees
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe1@email.com"
}

###

GET http://localhost:3333/events/8beca352-9c53-4b55-8bc4-512af96d7efc
###

GET http://localhost:3333/attendees/4652e889aa/badge

###

GET http://localhost:3333/attendees/4652e889aa/check-in

###

GET http://localhost:3333/events/8beca352-9c53-4b55-8bc4-512af96d7efc/attendees?query=John